---
name: ci

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and test - OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['23.2']
        elixir: ['1.11.4']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir ${{matrix.elixir}}
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{matrix.otp}}
        experimental-otp: true

    - name: Retrieve dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

    - name: Retrieve build cache
      uses: actions/cache@v2
      with:
        path: _build
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Check formatting
      run: mix format --check-formatted

    - name: Compile project
      run: |
          MIX_ENV=test mix compile --warnings-as-errors
          MIX_ENV=dev mix compile --warnings-as-errors

    - name: Run tests
      run: |
        epmd -daemon
        mix test --include distributed

    - name: Retrieve Dialyzer PLT cache
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles('**/mix.lock') }}

    - name: Create Dialyzer PLTs
      if: steps.plt-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mix check

    - name: Static code analysis
      run: mix check
